CacheChooserController robustness
ConnorDY/OSRS-Environment-Exporter pull request #113
Opened 2022-08-18 01:51 UTC by ScoreUnder

2022-08-18 02:13 UTC, ConnorDY commented on src/main/kotlin/controllers/CacheChooserController.kt
> +                btnDownload.isEnabled = selectedIndex != -1
I would add a `CHANGELOG.md` entry under "Bug Fixes" for this.

2022-08-18 02:13 UTC, ConnorDY commented on src/main/kotlin/controllers/CacheChooserController.kt
> +                })
Does this address my comment on this issue:
https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/57#issuecomment-1212690497

2022-08-18 02:15 UTC, ConnorDY requested changes
As part of this PR, could you also address my comment on this issue:
https://github.com/ConnorDY/OSRS-Environment-Exporter/issues/57#issuecomment-1212690497

If so, let's add an entry to `CHANGELOG.md` for this and close out that ticket.

2022-08-18 02:16 UTC, ConnorDY requested changes

2022-08-18 02:16 UTC, ConnorDY commented on src/main/kotlin/controllers/CacheChooserController.kt
> +        }
I would add a `CHANGELOG.md` entry under "Bug Fixes" for this.

2022-08-18 11:39 UTC, ScoreUnder commented
I've suppressed the stack trace for the JSON parse failure (test it out by putting a random character into your xteas json lol) but otherwise not sure what you mean with the error message thing, it seems like it already did that?

2022-08-19 23:26 UTC, ConnorDY approved these changes

2022-08-19 23:36 UTC, merged